const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Behaviors.MoveTo,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Behaviors.Turret,
		C3.Behaviors.LOS,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Acts.SubInstanceVar,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{caverna: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Apollo: 0},
	{VáEsquerda: 0},
	{Slime: 0},
	{Mosca: 0},
	{Tv_v: 0},
	{Projétil: 0},
	{Bolinha_Tv: 0},
	{atacar: 0},
	{Senóide: 0},
	{Prysmeye: 0},
	{MoverPara: 0},
	{Ataque_Boss_1: 0},
	{Ataque_Boss_2: 0},
	{Fundo: 0},
	{portaBoss: 0},
	{limite_slime: 0},
	{limite_mosca: 0},
	{hitbox_dano: 0},
	{Borda_barra_de_vida_Boss: 0},
	{porta: 0},
	{Fixar: 0},
	{Canhão: 0},
	{CampoDeVisão: 0},
	{espinhos: 0},
	{Teclado: 0},
	{area_de_ativação: 0},
	{Sprite: 0},
	{Mouse: 0},
	{bolinha_personagem: 0},
	{VIDA: 0},
	{Barra_de_vida_boss: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Texto: 0},
	{Apollo2: 0},
	{Partículas: 0},
	{Sprite4: 0},
	{Partículas2: 0},
	{bolinha_personagem2: 0},
	{Prysmeye2: 0},
	{Tv_v2: 0},
	{Ataque_Boss_3: 0},
	{Mosca2: 0},
	{Slime2: 0},
	{Sprite5: 0},
	{Texto2: 0},
	{Boss_ativo: 0}
];

self.InstanceType = {
	caverna: class extends self.ITilemapInstance {},
	Apollo: class extends self.ISpriteInstance {},
	Slime: class extends self.ISpriteInstance {},
	Mosca: class extends self.ISpriteInstance {},
	Tv_v: class extends self.ISpriteInstance {},
	Bolinha_Tv: class extends self.ISpriteInstance {},
	Prysmeye: class extends self.ISpriteInstance {},
	Ataque_Boss_1: class extends self.ISpriteInstance {},
	Ataque_Boss_2: class extends self.ISpriteInstance {},
	Fundo: class extends self.ITiledBackgroundInstance {},
	portaBoss: class extends self.ISpriteInstance {},
	limite_slime: class extends self.ISpriteInstance {},
	limite_mosca: class extends self.ISpriteInstance {},
	hitbox_dano: class extends self.ISpriteInstance {},
	Borda_barra_de_vida_Boss: class extends self.ISpriteInstance {},
	porta: class extends self.ITiledBackgroundInstance {},
	Canhão: class extends self.ISpriteInstance {},
	espinhos: class extends self.ITilemapInstance {},
	Teclado: class extends self.IInstance {},
	area_de_ativação: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	bolinha_personagem: class extends self.ISpriteInstance {},
	Barra_de_vida_boss: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Apollo2: class extends self.ISpriteInstance {},
	Partículas: class extends self.IParticlesInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Partículas2: class extends self.IParticlesInstance {},
	bolinha_personagem2: class extends self.ISpriteInstance {},
	Prysmeye2: class extends self.ISpriteInstance {},
	Tv_v2: class extends self.ISpriteInstance {},
	Ataque_Boss_3: class extends self.ISpriteInstance {},
	Mosca2: class extends self.ISpriteInstance {},
	Slime2: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {}
}